#!/bin/bash
# 1. start cLab
make start
# 2. build configs with AVD
make build
# 3. create CVP change control 
make deploy_cvp
# 4. assign tags for CVP topology view 
make tags
# 5. validate the deployment with ANTA preview
make test